import React, { useState } from 'react';
import { FileText, Download, Copy, Sparkles, Wand2, Zap, Star } from 'lucide-react';

interface ContentTemplate {
  id: string;
  name: string;
  platform: string;
  type: 'post' | 'description' | 'bio';
  template: string;
  color: string;
  gradient: string;
}

const AIContentGenerator: React.FC = () => {
  const [selectedTemplate, setSelectedTemplate] = useState<string>('');
  const [generatedContent, setGeneratedContent] = useState<string>('');
  const [isGenerating, setIsGenerating] = useState(false);

  const templates: ContentTemplate[] = [
    {
      id: 'instagram-post',
      name: 'Instagram Post',
      platform: 'Instagram',
      type: 'post',
      template: 'Create an engaging Instagram post about our new music release...',
      color: '#E4405F',
      gradient: 'linear-gradient(135deg, #E4405F 0%, #F77737 100%)'
    },
    {
      id: 'twitter-thread',
      name: 'Twitter Thread',
      platform: 'Twitter',
      type: 'post',
      template: 'Craft a compelling Twitter thread introducing our latest track...',
      color: '#1DA1F2',
      gradient: 'linear-gradient(135deg, #1DA1F2 0%, #42A5F5 100%)'
    },
    {
      id: 'album-description',
      name: 'Album Description',
      platform: 'Spotify',
      type: 'description',
      template: 'Write an captivating album description that draws listeners in...',
      color: '#1DB954',
      gradient: 'linear-gradient(135deg, #1DB954 0%, #4CAF50 100%)'
    },
    {
      id: 'artist-bio',
      name: 'Artist Bio',
      platform: 'Website',
      type: 'bio',
      template: 'Create an artist biography that showcases our unique sound...',
      color: '#FF6B35',
      gradient: 'linear-gradient(135deg, #FF6B35 0%, #F7931E 100%)'
    }
  ];

    const generateContent = async () => {
    if (!selectedTemplate) return;

    setIsGenerating(true);
    // Simulate AI generation
    setTimeout(() => {
      const template = templates.find(t => t.id === selectedTemplate);
      setGeneratedContent(`🚀 **${template?.name} Generated by AI**

✨ Experience the magic of our latest creation! This track captures the essence of modern music with innovative beats and soul-stirring melodies.

🎵 **Key Features:**
• Innovative production techniques
• Emotional depth and storytelling
• Perfect for playlists and radio

#MusicMarketing #AIContent #HardbanRecords

---
*Generated by Prometheus AI - Advanced Content Creation*`);
      setIsGenerating(false);
    }, 2000);
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(generatedContent);
  };

  const containerStyle = {
    padding: '0',
    background: 'transparent',
    borderRadius: '0',
    minHeight: 'auto'
  };

  const templateCardStyle = (isSelected: boolean, gradient: string) => ({
    padding: '24px',
    borderRadius: '16px',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    border: isSelected ? '2px solid rgba(255, 255, 255, 0.3)' : '1px solid rgba(255, 255, 255, 0.1)',
    background: isSelected
      ? `linear-gradient(135deg, ${gradient.split(',')[1]?.trim() || '#667eea'} 0%, rgba(255,255,255,0.1) 100%)`
      : 'linear-gradient(135deg, rgba(255,255,255,0.05) 0%, rgba(255,255,255,0.02) 100%)',
    backdropFilter: 'blur(10px)',
    boxShadow: isSelected
      ? '0 15px 35px rgba(0, 0, 0, 0.3), 0 0 30px rgba(255, 255, 255, 0.1)'
      : '0 8px 25px rgba(0, 0, 0, 0.2)',
    transform: isSelected ? 'translateY(-5px) scale(1.02)' : 'translateY(0) scale(1)'
  });

  const generateButtonStyle = {
    width: '100%',
    padding: '20px',
    borderRadius: '16px',
    fontSize: '18px',
    fontWeight: '600',
    border: 'none',
    cursor: isGenerating || !selectedTemplate ? 'not-allowed' : 'pointer',
    transition: 'all 0.3s ease',
    background: isGenerating || !selectedTemplate
      ? 'linear-gradient(135deg, rgba(128,128,128,0.3) 0%, rgba(64,64,64,0.3) 100%)'
      : 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    color: isGenerating || !selectedTemplate ? '#666' : '#ffffff',
    boxShadow: isGenerating || !selectedTemplate
      ? 'none'
      : '0 10px 30px rgba(102, 126, 234, 0.4)',
    transform: isGenerating || !selectedTemplate ? 'none' : 'translateY(0)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '12px'
  };

  const contentAreaStyle = {
    background: 'linear-gradient(135deg, rgba(0,0,0,0.3) 0%, rgba(0,0,0,0.1) 100%)',
    border: '1px solid rgba(255, 255, 255, 0.1)',
    borderRadius: '16px',
    padding: '24px',
    minHeight: '300px',
    backdropFilter: 'blur(10px)',
    boxShadow: '0 8px 25px rgba(0, 0, 0, 0.2)',
    fontFamily: 'monospace',
    whiteSpace: 'pre-wrap' as const,
    color: '#e0e7ff',
    fontSize: '14px',
    lineHeight: '1.6'
  };

  const actionButtonStyle = {
    padding: '12px 20px',
    borderRadius: '12px',
    border: 'none',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: '600',
    transition: 'all 0.3s ease',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    background: 'linear-gradient(135deg, #4CAF50 0%, #45a049 100%)',
    color: '#ffffff',
    boxShadow: '0 4px 15px rgba(76, 175, 80, 0.3)'
  };

  return (
    <div style={containerStyle}>
      <div style={{ marginBottom: '40px' }}>
        <div style={{
          display: 'flex',
          alignItems: 'center',
          gap: '16px',
          marginBottom: '30px',
          justifyContent: 'center'
        }}>
          <div style={{
            background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
            borderRadius: '16px',
            padding: '16px',
            boxShadow: '0 8px 25px rgba(102, 126, 234, 0.3)'
          }}>
            <Wand2 size={32} color="#ffffff" />
          </div>
          <div>
            <h2 style={{
              fontSize: '2.2rem',
              fontWeight: '800',
              margin: '0 0 8px 0',
              background: 'linear-gradient(135deg, #ffffff 0%, #e0e7ff 100%)',
              WebkitBackgroundClip: 'text',
              WebkitTextFillColor: 'transparent'
            }}>
              AI Content Generator
            </h2>
            <p style={{
              fontSize: '1.1rem',
              margin: 0,
              color: '#b8c5ff',
              fontWeight: '300'
            }}>
              Create engaging marketing content with advanced AI technology
            </p>
          </div>
        </div>

        <div style={{ marginBottom: '40px' }}>
          <h3 style={{
            fontSize: '1.4rem',
            fontWeight: '700',
            marginBottom: '20px',
            color: '#ffffff',
            textAlign: 'center'
          }}>
            Choose Your Content Template
          </h3>
          <div style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
            gap: '20px'
          }}>
            {templates.map((template) => {
              const isSelected = selectedTemplate === template.id;
              return (
                <div
                  key={template.id}
                  onClick={() => setSelectedTemplate(template.id)}
                  style={templateCardStyle(isSelected, template.gradient)}
                  onMouseEnter={(e) => {
                    if (!isSelected) {
                      e.currentTarget.style.transform = 'translateY(-3px) scale(1.01)';
                      e.currentTarget.style.boxShadow = '0 12px 30px rgba(0, 0, 0, 0.25)';
                    }
                  }}
                  onMouseLeave={(e) => {
                    if (!isSelected) {
                      e.currentTarget.style.transform = 'translateY(0) scale(1)';
                      e.currentTarget.style.boxShadow = '0 8px 25px rgba(0, 0, 0, 0.2)';
                    }
                  }}
                >
                  <div style={{
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'space-between',
                    marginBottom: '16px'
                  }}>
                    <div style={{
                      background: template.gradient,
                      borderRadius: '12px',
                      padding: '8px',
                      boxShadow: '0 4px 15px rgba(0, 0, 0, 0.2)'
                    }}>
                      <FileText size={24} color="#ffffff" />
                    </div>
                    {isSelected && (
                      <div style={{
                        background: 'linear-gradient(135deg, #ffd700 0%, #ffed4e 100%)',
                        borderRadius: '50%',
                        padding: '4px',
                        boxShadow: '0 2px 10px rgba(255, 215, 0, 0.3)'
                      }}>
                        <Star size={16} color="#ffffff" fill="#ffffff" />
                      </div>
                    )}
                  </div>

                  <div>
                    <h4 style={{
                      fontSize: '1.2rem',
                      fontWeight: '700',
                      margin: '0 0 4px 0',
                      color: '#ffffff'
                    }}>
                      {template.name}
                    </h4>
                    <p style={{
                      fontSize: '0.9rem',
                      margin: '0 0 12px 0',
                      color: template.color,
                      fontWeight: '600'
                    }}>
                      {template.platform}
                    </p>
                    <p style={{
                      fontSize: '0.95rem',
                      margin: 0,
                      color: '#b8c5ff',
                      lineHeight: '1.4'
                    }}>
                      {template.template}
                    </p>
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        <div style={{ marginBottom: '40px' }}>
          <button
            onClick={generateContent}
            disabled={!selectedTemplate || isGenerating}
            style={generateButtonStyle}
            onMouseEnter={(e) => {
              if (!isGenerating && selectedTemplate) {
                e.currentTarget.style.transform = 'translateY(-2px)';
                e.currentTarget.style.boxShadow = '0 15px 40px rgba(102, 126, 234, 0.5)';
              }
            }}
            onMouseLeave={(e) => {
              if (!isGenerating && selectedTemplate) {
                e.currentTarget.style.transform = 'translateY(0)';
                e.currentTarget.style.boxShadow = '0 10px 30px rgba(102, 126, 234, 0.4)';
              }
            }}
          >
            {isGenerating ? (
              <>
                <div style={{
                  width: '24px',
                  height: '24px',
                  border: '3px solid rgba(255,255,255,0.3)',
                  borderTop: '3px solid #ffffff',
                  borderRadius: '50%',
                  animation: 'spin 1s linear infinite'
                }}></div>
                Generating with AI...
              </>
            ) : (
              <>
                <Sparkles size={24} />
                Generate Content
                <Zap size={20} />
              </>
            )}
          </button>
        </div>

        {/* Generated Content */}
        <div>
          <h3 style={{
            fontSize: '1.4rem',
            fontWeight: '700',
            marginBottom: '20px',
            color: '#ffffff',
            textAlign: 'center'
          }}>
            Generated Content
          </h3>

          <div style={contentAreaStyle}>
            {generatedContent ? (
              <div>
                <div style={{
                  background: 'linear-gradient(135deg, rgba(255,255,255,0.1) 0%, rgba(255,255,255,0.05) 100%)',
                  borderRadius: '8px',
                  padding: '16px',
                  marginBottom: '16px',
                  border: '1px solid rgba(255, 255, 255, 0.1)'
                }}>
                  {generatedContent}
                </div>
                <div style={{
                  display: 'flex',
                  gap: '12px',
                  justifyContent: 'center'
                }}>
                  <button
                    onClick={copyToClipboard}
                    style={actionButtonStyle}
                    onMouseEnter={(e) => {
                      e.currentTarget.style.transform = 'translateY(-2px)';
                      e.currentTarget.style.boxShadow = '0 6px 20px rgba(76, 175, 80, 0.4)';
                    }}
                    onMouseLeave={(e) => {
                      e.currentTarget.style.transform = 'translateY(0)';
                      e.currentTarget.style.boxShadow = '0 4px 15px rgba(76, 175, 80, 0.3)';
                    }}
                  >
                    <Copy size={16} />
                    Copy to Clipboard
                  </button>
                  <button
                    onClick={() => setGeneratedContent('')}
                    style={{
                      ...actionButtonStyle,
                      background: 'linear-gradient(135deg, #FF6B6B 0%, #ee5a52 100%)',
                      boxShadow: '0 4px 15px rgba(255, 107, 107, 0.3)'
                    }}
                    onMouseEnter={(e) => {
                      e.currentTarget.style.transform = 'translateY(-2px)';
                      e.currentTarget.style.boxShadow = '0 6px 20px rgba(255, 107, 107, 0.4)';
                    }}
                    onMouseLeave={(e) => {
                      e.currentTarget.style.transform = 'translateY(0)';
                      e.currentTarget.style.boxShadow = '0 4px 15px rgba(255, 107, 107, 0.3)';
                    }}
                  >
                    <Download size={16} />
                    Clear
                  </button>
                </div>
              </div>
            ) : (
              <div style={{
                display: 'flex',
                flexDirection: 'column',
                alignItems: 'center',
                justifyContent: 'center',
                height: '200px',
                color: '#666'
              }}>
                <Sparkles size={48} color="#666" style={{ marginBottom: '16px', opacity: 0.5 }} />
                <p style={{ fontSize: '1.1rem', color: '#b8c5ff', textAlign: 'center' }}>
                  Select a template and click &quot;Generate Content&quot; to create AI-powered marketing content
                </p>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default AIContentGenerator;
